export const STORAGE_KEY = "shopping_list_v2";

export const DEFAULT_BUCKETS = [
  {
    id: "alimentari-di-base",
    group: "Alimentari di base",
    items: [
      "Pasta",
      "Tortellini",
      "Quadrucci",
      "Riso",
      "Ravioli",
      "Lenticchie",
      "Ceci",
      "Fagioli",
      "Tonno",
      "Passata",
      "Cipolle",
      "Aglio",
      "Porro",
      "Carote",
      "Zucchine",
      "Pomodorini",
      "Odori misti",
      "Valeriana",
      "Sedano",
      "Cavolo",
      "Mele",
      "Banane",
      "Mandarini",
      "Arancie",
      "Uova",
      "Latte",
      "Burro",
      "Philadelphia",
      "Mozzarella",
      "Prosciutto Cotto",
      "Prosciutto Crudo",
      "Edamer",
      "Grana",
      "Sottiletta",
      "Pane",
      "Schiacciata",
      "Olio",
      "Olio per frittura",
      "Sale",
      "Pepe",
      "Maionese",
      "Ketchup",
      "Caffe",
      "Te",
      "Zucchero",
      "Lesso",
    ],
  },
  {
    id: "bibite",
    group: "Bibite",
    items: ["Birra", "Succhi", "Vino"],
  },
  {
    id: "freschi",
    group: "Freschi",
    items: [
      "Yogurt",
      "Pollo",
      "Carpaccio",
      "Salsiccia",
      "Hamburger",
      "Macinato",
      "Salmone",
      "Nasello",
      "Bastoncini",
      "Crocchette",
      "Sofficini",
      "Pizza",
      "Piselli",
    ],
  },
  {
    id: "casa",
    group: "Casa",
    items: [
      "Carta igienica",
      "Scottex",
      "Carta alluminio",
      "Carta da forno",
      "Sacchetti per la spazzatura",
      "Sapone per le mani",
      "Shampoo",
      "Balsamo",
      "Dentifricio",
      "Deodorante",
      "Detersivo per piatti",
      "Spugna",
      "Sgrassatore",
      "Anticalcare",
      "Detergente per vetri",
      "Detersivo per lavatrice",
      "Ammorbidente",
      "Candeggina",
      "Detergente per WC",
      "Detergente per pavimenti",
    ],
  },
];
